.TH MKDICT 1
.SH NAME
mkdict \- generate a dictionary from the web

.SH SYNOPSIS
mkdict LINK COUNT

.SH DESCRIPTION
mkdict is a fairly simple shell script that crawls one or more websites
to generate a dictionary. LINK sets the starting link and COUNT determines the
number of pages that should be used to generate the dictionary.

.SH FILES
.I dict
.RS
the resulting dictionary. Each line contains two fields, the first being the frequency
of the word in words per million, the second one being the word itself.
.RE
.I
data
.RS
a directory for keeping the cached webpages.
.RE
.I
links
.RS
a temporary file where the downloaded links are saved.
.RE

.SH EXAMPLES
.PP
.fi
.RS
$ mkdict https://en.wikipedia.org/wiki/Main_Page 10000
.RE
.fi
generates a dictionary from 10000 wikipedia pages.

.SH STATUS
0 on success and 1 when it prints the usage.

.SH BUGS
The only configuration is provided by editing the source code, which is
quite unpleasant.
.P
Caching of the downloaded webpages fills the harddrive. Run make clean to
delay the problem.

.SH AUTHOR
Send bugs and ants to pranomestro@gmail.com
