.Dd May 11, 2017
.Dt MKDICT 1
.Os

.Sh NAME
.Nm mkdict
.Nd generate a dictionary from the web

.Sh SYNOPSIS
.Nm
.Ar link
.Ar count

.Sh DESCRIPTION
.Nm
is a shell script that crawls one or more websites to generate a dictionary.
.Ar link
sets the starting link and
.Ar count
determines the number of pages that should be used to generate the dictionary.

.Sh FILES
.Bl -tag -width Ds
.It Pa dict
The resulting dictionary. Each line contains two fields, the first being
the frequency of the word in words per million, the second one being
the word itself.
.It Pa links
A temporary file for saving the links.
.It Pa data
A cache directory for the keeping the webpages.
.El

.Sh EXAMPLES
Generate a dictionary from 10000 wikipedia pages:
.Pp
.Dl $ mkdict https://en.wikipedia.org/wiki/Main_Page 10000

.Sh EXIT STATUS
.Ex -std

.Sh BUGS
.Nm
is configured by editing its source code.
.Pp
Caching of the webpages fills the harddrive.

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
